version: '3.9'

services:
  server:
    build:
      context: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - taaskly

  database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: taaskly
    ports:
      - 27017:27017
    networks:
      - taaskly

networks:
  taaskly: