version: '3.9'

services:
  local_database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: taaskly
    ports:
      - 27017:27017
    networks:
      - taaskly

networks:
  taaskly:
